### ISSUE TITLE
Failed to import DICOM (containing JPG slices)

### ISSUE THREAD

**Issue by chiaradivece** [mlavik1/UnityVolumeRendering#36] opened 2020-11-24 18:35 UTC
Hi! First, thanks for this amazing work! I'm struggling to import DICOM models. I have a folder with .dcm files (each one corresponding to a CT slice). When I select the folder in which the files are, I get this error:

_InvalidCastException: Specified cast is not valid.
System.Convert.ToInt32 (System.Object value) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityVolumeRendering.DICOMImporter.ToPixelArray (openDicom.Image.PixelData pixelData) (at Assets/Scripts/Importing/DICOMImporter.cs:202)
UnityVolumeRendering.DICOMImporter.Import () (at Assets/Scripts/Importing/DICOMImporter.cs:94)
UnityVolumeRendering.VolumeRendererEditorFunctions.ShowDICOMImporter () (at Assets/Editor/VolumeRendererEditorFunctions.cs:30)_

I've also tried with another dataset, and the error is this:

_Problems processing the DICOM file /Users/chiara/Downloads/TRAUMA/trauma0730.dcm :
 System.ArgumentException: Item has already been added. Key in dictionary: '(0002,0002)'  Key being added: '(0002,0002)'
  at System.Collections.Hashtable.Insert (System.Object key, System.Object nvalue, System.Boolean add) [0x001d4] in <9577ac7a62ef43179789031239ba8798>:0 
  at System.Collections.Hashtable.Add (System.Object key, System.Object value) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at openDicom.DataStructure.DataSet.DataSet.Add (openDicom.DataStructure.DataSet.DataElement dataElement) [0x00009] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/DataStructure/DataSet/DataSet.cs:113 
  at openDicom.DataStructure.DataSet.DataSet.Add (openDicom.DataStructure.DataSet.DataSet dataSet) [0x00017] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/DataStructure/DataSet/DataSet.cs:126 
  at openDicom.File.DicomFile.GetJointDataSets () [0x00014] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/File/DicomFile.cs:157 
  at openDicom.File.DicomFile.LoadFrom (System.IO.Stream stream) [0x00042] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/File/DicomFile.cs:133 
  at openDicom.File.AcrNemaFile..ctor (System.String fileName, System.Boolean useStrictDecoding) [0x00028] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/File/AcrNemaFile.cs:131 
  at openDicom.File.DicomFile..ctor (System.String fileName, System.Boolean useStrictDecoding) [0x00007] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/3rdparty/openDicom/File/DicomFile.cs:83 
  at UnityVolumeRendering.DICOMImporter.LoadFile (System.String filePath) [0x0000e] in /Users/chiara/GitHub/UnityVolumeRendering/Assets/Scripts/Importing/DICOMImporter.cs:180 
UnityEngine.Debug:LogError(Object)
UnityVolumeRendering.DICOMImporter:LoadFile(String) (at Assets/Scripts/Importing/DICOMImporter.cs:188)
UnityVolumeRendering.DICOMImporter:ReadDICOMFile(String) (at Assets/Scripts/Importing/DICOMImporter.cs:125)
UnityVolumeRendering.DICOMImporter:Import() (at Assets/Scripts/Importing/DICOMImporter.cs:61)
UnityVolumeRendering.VolumeRendererEditorFunctions:ShowDICOMImporter() (at Assets/Editor/VolumeRendererEditorFunctions.cs:30)_

I tried to open the datasets in a DICOM visualization system and they seem just fine. Many thanks in advance!

**Comment by mlavik1** [comment] 2020-11-25 12:10
Hi! Thanks for reporting this issue.

Do you know if your dataset uses JPEG format?
I think there is a mistake in how I'm handling DICOM sequences. I managed to fix the issue, but then I encountered another issue: Many DICOM files that use JPEG don't have a JPEG header, so I'm not able to import the JPEG bytes properly. I'm not sure how I'll fix this, but I'll keep looking into it. (@MusoAga maybe you know?)

By the way, is this an open dataset that you can share with me?
If not, I seem to have one dataset where I can reproduce the same issue :)

**Comment by chiaradivece** [comment] 2020-11-25 13:14
Hi @mlavik1,
thanks for the prompt reply!
I'm not sure about the format; however, the first dataset that I was testing is available. You can download it from the DICOM Library website at this link: https://www.dicomlibrary.com/meddream/?study=1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170

Thanks for the help!

**Comment by mlavik1** [comment] 2020-11-25 15:44
@chiaradivece Thanks for sharing!
I did a quick test, and it seems to be the same problem. The dataset contains JPEG data without a header.
I will try to add support for this, but it might take some time (since I have less time for personal projects now), but I'll do my best!

For now, you can import your dataset if you export it as an image sequence like this:
![image](https://user-images.githubusercontent.com/6906872/100249527-f0d58380-2f3c-11eb-82e9-e1492fd17e01.png)
(I used JPEG, but all of them should work)
And then you can import it into Unity by clicking this button instead:
![image](https://user-images.githubusercontent.com/6906872/100249606-09459e00-2f3d-11eb-9064-f05feff4d636.png)
The quality might be better with DICOM, but I did a test and your dataset looks like this (after eding the TF and enabling lighting):
![image](https://user-images.githubusercontent.com/6906872/100249851-51fd5700-2f3d-11eb-9c6c-f4a0924a20b6.png)
And this is with maximum intensity projection:
![image](https://user-images.githubusercontent.com/6906872/100249919-62adcd00-2f3d-11eb-8f83-a1a253e858ea.png)

I'll let you know if/when I have fixed the DICOM issue.
DICOM files that do not use JPEG should work though :)

**Comment by chiaradivece** [comment] 2020-11-27 09:40
Many thanks, @mlavik1! It works with png!

**Comment by mlavik1** [comment] 2020-11-27 11:33
@chiaradivece Good to hear!
I will keep this task open (but change the description) until I have done a fix for DICOM with JPG.
Have a nice day!

**Comment by chiaradivece** [comment] 2020-11-27 22:55
Hey @mlavik1, I wanted to point out another problem. I tried to upload another DICOM dataset (it works fine when I try to open in Slicer or similar). However, I get the following error:

_Insufficient number of slices.
UnityEngine.Debug:LogError(Object)
UnityVolumeRendering.DICOMImporter:Import() (at Assets/Scripts/Importing/DICOMImporter.cs:72)
UnityVolumeRendering.VolumeRendererEditorFunctions:ShowDICOMImporter() (at Assets/Editor/VolumeRendererEditorFunctions.cs:30)_

**Comment by mlavik1** [comment] 2020-11-28 10:45
Hello again!
Hmm.. is there another error before that error?
I suspect that it failed to import one or more slices, but if that's the case there should also be more errors in the log.

Also, is this a dataset that can be shared?

**Comment by chiaradivece** [comment] 2020-11-28 11:01
Hi @mlavik1! Mmm no, this is the first error that appears. I could try to share it with you. Thanks

**Comment by chiaradivece** [comment] 2020-11-28 11:06
Attachment available until Dec 28, 2020
Hey! Here is the dataset:

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAcgRBGHz3m620hgBtflSwcQ8gUOdAbstFj0McM1zophv3gEPXSzW4NP2%2F%24%7Bf%7D%3Fo%3DAiLNflny5vioM_ncfzCAV1hbVw_rjVm5mGYB-37iP-wk%26v%3D1%26x%3D3%26a%3DCAoglREX7_Gr3yIBcf4TeZqaJaHC9bi7SOj31uxvWce3i60SeRC9raL04C4Yvb2dyOouIgEAKggByAD_S3uwx1IEPIFDnVoE1uDT9mon-aGukmau9d5y1iLl4uDiGA4EfJTpryU-ATHehlnXtjc04MFoI1-fcieX4oAaUlzqJYZr00McgRMQ8yR8wXd0ZmeP9fvH8Ro9uVTkaa3TywM%26e%3D1609153601%26fl%3D%26r%3D2350C7F5-EC00-4E95-A9FC-3E3184590111-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D50905A11-E9CD-4D16-8730-1AF01637C3C0%26p%3D41%26s%3DBb_hfpGosVx6-DJ8H8DytFAcenM&uk=_aMDRpePl7UphAwcwa1jdg&f=BABY_GLASS.zip&sz=28344775>BABY_GLASS.zip
28.3 MB

**Comment by mlavik1** [comment] 2020-11-28 11:10
Thanks @chiaradivece !

**Comment by chiaradivece** [comment] 2020-11-28 11:15
Attachment available until Dec 28, 2020
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfWOTuFtVDjC3C8lm5q4E97IOtk_AZJjNs5mi3KOMW8cJp5Au8sJzpHZ%2F%24%7Bf%7D%3Fo%3DAjnpzsOs20erGlQvfcc7vxulux7VaBW_t_gL9x49-asl%26v%3D1%26x%3D3%26a%3DCAogiQP7NTP7jbsJk1C_HQDyrQX8MxoeaVb5p87GvLQe2JASeRDDy8D04C4Yw9u7yOouIgEAKggByAD_IKE0e1IEyDrZP1oECc6R2Won6P-tpembuSTEX4UNeoX1PFW4Oxy6DnS0TZsorP7UB1n67P_83P5ncifZGhDDq7VKXYqGU_QoRnPdIF5qTArphg1GIHlJmzjUL-Ul3WzZJPA%26e%3D1609154096%26fl%3D%26r%3D65C6D418-D21A-4BD4-86BD-49E95E616478-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D50905A11-E9CD-4D16-8730-1AF01637C3C0%26p%3D41%26s%3Dj7njRxcC7NM0peJgtaVrqYsGx_c&uk=flXUB5dndsnBm3S2EPwEkQ&f=Test.zip&sz=28344775>Test.zip
28.3 MB

**Comment by mlavik1** [comment] 2022-04-07 16:34
Fixed by #95 
The dataset can now be imported with SimpleITK (on Windows only for now).
![bilde](https://user-images.githubusercontent.com/6906872/162253005-94e7058a-ce7d-4b4f-9c31-afb5bcabcd53.png)

**Closed by mlavik1** 2022-04-07 16:34 UTC
