### ISSUE TITLE
Missing SimpleITK 

### ISSUE THREAD

**Issue by Meruja** [mlavik1/UnityVolumeRendering#134] opened 2022-11-20 20:33 UTC
I get this error when I try loading any dicom file. I have a .nii file and need simpleITK for it to work. However, it keeps prompting me that I need SimpleITK to be enabled when SimpleITK is already downloaded. Any help would be greatly appreciated.

![image](https://user-images.githubusercontent.com/28688743/202924598-ff7e6dca-ee80-4f88-8f28-557282c5a28f.png)

Unity version 2020.3.33f1
Steps to replicated:
1. Import EasyVolumeRendering
2. Try importing nifti
3. enable SimpleITK
4. Download simpleITK
5. Repeat step 2.

And it just keeps prompting with the above image.

**Comment by smallvalthoss** [comment] 2022-11-20 21:24
Same thing happens to me when using MRTK, SimpleITK stops getting recognized.

**Comment by mlavik1** [comment] 2022-11-21 07:39
Thanks for reporting this! :) 
I'll take a look at this after work, but I noticed one potential bug here. 
Are you using another build target than "Standaline"? (maybe WebGL or something?). If so, changing this line: `BuildTargetGroup group = BuildPipeline.GetBuildTargetGroup(target);` to this `BuildTargetGroup group = BuildTargetGroup.Standalone;` in line 25 in SimpleITKManager.cs might fix the issue.

**Comment by mlavik1** [comment] 2022-11-21 20:55
Hi again!
@Meruja You are trying to import a nifti file and not an NRRD file, right? Because SimpleITK is no longer a requirement (though maybe still recommended) for nifti-import, since #126. If you pull latest form master it should no longer be an issue (I'll probably make a release soon as well).

I've also created a PR with a fix for this issue happening when you've selected a different build target: #137 
@smallvalthoss does that fix the issue for you too?
If not, could you explain how I can reproduce it? Thanks :)

**Comment by Meruja** [comment] 2022-11-21 21:10
I'm using UWP for the target build device hololens 2 and trying to import a nifti file(heart.nii). As you suggested I made the changes in SimpleITKManager.cs file and now it fixes to identify the simpleITK. But it throws errors (shown in the image) when I try to load the nifti file. 
I just imported the Easy VolumeRendering package from the asset store instead of working with GitHub repository.
![Screenshot_20221121_020619](https://user-images.githubusercontent.com/28688743/203158207-c58fc5ab-c223-424d-af29-c118d28a3587.png)

**Comment by mlavik1** [comment] 2022-11-21 21:40
I'll see if I can reproduce this with the Asset Store version (Need to switch to my Windows machine, because of some Unity issue ). Need to go to sleep soon, so I'll look more at that tomorrow.

But I made a new unitypackage for you that you can try, if you don't mind using a "beta" version: https://github.com/mlavik1/UnityVolumeRendering/actions/runs/3518245412
Unity 2021: https://github.com/mlavik1/UnityVolumeRendering/suites/9431168676/artifacts/445763369
Unity 2019: https://github.com/mlavik1/UnityVolumeRendering/suites/9431168676/artifacts/445763368
([this](https://github.com/mlavik1/UnityVolumeRendering/actions/runs/3518245412) is the build btw)

The build is based on the latest un-published version.
You can import it by going to: Assets > Import Package > Custom Package
as described here: https://docs.unity3d.com/Manual/AssetPackagesImport.html
You need to remove the old "EasyVolumeRendering" folder first.

**Comment by Meruja** [comment] 2022-11-21 21:52
> I'll see if I can reproduce this with the Asset Store version (Need to switch to my Windows machine, because of some Unity issue ). Need to go to sleep soon, so I'll look more at that tomorrow.
> 
> But I made a new unitypackage for you that you can try, if you don't mind using a "beta" version: https://github.com/mlavik1/UnityVolumeRendering/actions/runs/3518245412 Unity 2021: https://github.com/mlavik1/UnityVolumeRendering/suites/9431168676/artifacts/445763369 Unity 2019: https://github.com/mlavik1/UnityVolumeRendering/suites/9431168676/artifacts/445763368 ([this](https://github.com/mlavik1/UnityVolumeRendering/actions/runs/3518245412) is the build btw)
> 
> The build is based on the latest un-published version. You can import it by going to: Assets > Import Package > Custom Package as described here: https://docs.unity3d.com/Manual/AssetPackagesImport.html You need to remove the old "EasyVolumeRendering" folder first.

That's totally fine. I'll try the beta version and update the results. Thanks

**Comment by mlavik1** [comment] 2022-11-22 20:23
Great! Let me know if that worked, please :)
I'll try on Windows with asset store version now.

**Comment by mlavik1** [comment] 2022-11-22 21:36
Ok, so I found the cause of the bug:
I add a `UVR_USE_SIMPLEITK` definition to the standalone build target when enabling SimpleITK, and then check if this is defined in the code when importing. However, if you select another build target then it won't know that SImpleITK is enabled and available while in the editor.
I'll see if I can find some way of adding definitions to the editor :thinking: 

Until then you can:
A: Use the unitypackage I sent you, which supports NIFTI without SimpleITK (I expect it should also work in your UWP build)
B: Switch build target to standalone before you import, and then switch back afterwards.

SimpleITK does not work on UWP builds at the moment though. But I think adding support for that should just be a matter of adding `BuildTargetGroup.WSA` to the `buildTargetGroups` array in SimpleITKManager.cs, like this:
```csharp
List<BuildTargetGroup> buildTargetGroups = new List<BuildTargetGroup> (){ BuildTargetGroup.Standalone, BuildTargetGroup.WSA };
```
And then disabling and enabling SimpleITK in the settings menu. 
I've never build for UWP/WSA before, but I'll see if I can give it a try tomorrow, and push a fix if that works.

**Closed** 2022-12-09 22:19 UTC
