### ISSUE TITLE
.dic file format data import error

### ISSUE THREAD

**Issue by SDSZR** [mlavik1/UnityVolumeRendering#24] opened 2020-07-29 08:03 UTC
![image](https://user-images.githubusercontent.com/11844783/88773621-ee446680-d1b4-11ea-9097-2f7237081c85.png)
Problems processing the DICOM file F:/femaleCT\IMG-0001-00001.dcm :
 openDicom.Encoding.EncodingException:
   Date time format is invalid.
Context:
   Tag:            (0008,002A)
   StreamPosition: 588
   ParamName:      DT/item
   ParamValue:     20180327205540.128000 
StackTrace:
  at openDicom.Encoding.DateTime.DecodeImproper (System.Byte[] bytes) [0x001a5] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\Encoding\DT.cs:92 
  at openDicom.DataStructure.ValueRepresentation.Decode (System.Byte[] bytes) [0x00014] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\VR.cs:518 
  at openDicom.DataStructure.Value.LoadFrom (System.IO.Stream stream) [0x000e0] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\Value.cs:354 
  at openDicom.DataStructure.Value..ctor (System.IO.Stream stream, openDicom.DataStructure.ValueRepresentation vr, openDicom.DataStructure.ValueLength length) [0x0000a] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\Value.cs:315 
  at openDicom.DataStructure.DataSet.DataElement.LoadFrom (System.IO.Stream stream) [0x00037] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\DataSet\DataElement.cs:172 
  at openDicom.DataStructure.DataSet.DataElement..ctor (System.IO.Stream stream, openDicom.Encoding.TransferSyntax transferSyntax) [0x00037] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\DataSet\DataElement.cs:143 
  at openDicom.DataStructure.DataSet.DataSet.LoadFrom (System.IO.Stream stream) [0x00023] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\DataSet\DataSet.cs:95 
  at openDicom.DataStructure.DataSet.Sequence..ctor (System.IO.Stream stream, openDicom.Encoding.TransferSyntax transferSyntax) [0x0002e] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\DataSet\Sequence.cs:127 
  at openDicom.DataStructure.DataSet.DataSet..ctor (System.IO.Stream stream, openDicom.Encoding.TransferSyntax transferSyntax) [0x0000b] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\DataStructure\DataSet\DataSet.cs:81 
  at openDicom.File.DicomFile.LoadFrom (System.IO.Stream stream) [0x00030] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\File\DicomFile.cs:132 
  at openDicom.File.AcrNemaFile..ctor (System.String fileName, System.Boolean useStrictDecoding) [0x00028] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\File\AcrNemaFile.cs:131 
  at openDicom.File.DicomFile..ctor (System.String fileName, System.Boolean useStrictDecoding) [0x00007] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\3rdparty\openDicom\File\DicomFile.cs:83 
  at UnityVolumeRendering.DICOMImporter.LoadFile (System.String filePath) [0x0000e] in Q:\workspace\Unity\Test\UnityVolumeRendering\Assets\Scripts\Importing\DICOMImporter.cs:164 
UnityEngine.Debug:LogError(Object)
UnityVolumeRendering.DICOMImporter:LoadFile(String) (at Assets/Scripts/Importing/DICOMImporter.cs:172)
UnityVolumeRendering.DICOMImporter:ReadDICOMFile(String) (at Assets/Scripts/Importing/DICOMImporter.cs:116)
UnityVolumeRendering.DICOMImporter:Import() (at Assets/Scripts/Importing/DICOMImporter.cs:59)
UnityVolumeRendering.VolumeRendererEditorFunctions:ShowDICOMImporter() (at Assets/Editor/VolumeRendererEditorFunctions.cs:30)

**Comment by mlavik1** [comment] 2020-07-29 10:39
Thanks! I'll have a look at it.
By the way, is this a publicly available dataset that I can download and test? (if not, I'll see if I can make a repro case).

**Comment by SDSZR** [comment] 2020-08-01 07:36
Sorry, these data are not public data sets. They contain some patient information, but we can confirm that there is a problem with Tag DT, which is the time format. Hope this can be helpful to you. Thank you for your reply!

**Comment by SDSZR** [comment] 2020-08-01 07:38
![image](https://user-images.githubusercontent.com/11844783/89096937-06162780-d40d-11ea-96b2-a65ae0ca68d8.png)

**Comment by mlavik1** [comment] 2020-08-19 15:51
Thank you!
Yes, I'll see if I can create a test dataset with the same issue.

As a hack-fix you could try opening the script "DT.cs" replacing the "throw new...." at line 92 with this: "dateTime[0] = System.DateTime.Now;".

And sorry for the late reply. I had holiday and haven't worked on any hobby-projects for a while now.
Hoping to get more time to work in this project again soon.

**Comment by SDSZR** [comment] 2020-08-21 02:35
Thank you for your reply. The project you have done has helped us a lot, but we encountered a new problem in the process of using it, which is the deformation of the rendered volume data after importing our DICOM data.
Like this:
**normal**
![image](https://user-images.githubusercontent.com/11844783/90846019-eafa6000-e399-11ea-87b4-a3eac07d037d.png)
**Deformation**
![image](https://user-images.githubusercontent.com/11844783/90846054-fbaad600-e399-11ea-92cb-037063c0c32b.png)
![image](https://user-images.githubusercontent.com/11844783/90846068-01a0b700-e39a-11ea-8df9-943b3beb5b70.png)
![image](https://user-images.githubusercontent.com/11844783/90846085-08c7c500-e39a-11ea-83fe-d87f179e4447.png)

**Comment by mlavik1** [comment] 2020-08-21 08:31
Glad to hear that you managed to import the dataset! (did the fix I suggested work?)

Ah, yes.. this happens because the volume data is loaded into a cube with a fixed size.
The fix should be rather simple: scale the box based on the X,Y,Z dimension of the dataset, but in the case of DICOM I guess the actual width/height/depth is available through some attribute?
I can take a look at this after work today or during the weekend :)
Until then I guess you could scale the box manually in the Unity Editor, but I'll try to get a fix for this as soon as I can. I'll let you know when I have something you can test.

And thanks a lot for the feedback!

**Comment by SDSZR** [comment] 2020-09-01 08:31
Hi, I'm sorry. Recently, due to other things, the response has been slower. Thank you for your active response. I pulled the branch you told me to solve the problem of body data compression. Thank you again for your help. , But there is still a small problem I don’t know how to solve as shown below:
![image](https://user-images.githubusercontent.com/11844783/91826353-0ace3580-ec70-11ea-9c0c-3256fa296bb2.png)
How to deal with something like this kind of vague?
Oh, I forgot to show you a zoomed and normal image, like the following:
![image](https://user-images.githubusercontent.com/11844783/91826731-8fb94f00-ec70-11ea-902c-91fc21621351.png)

**Comment by mlavik1** [comment] 2020-09-01 09:07
Hello again!
Great, looks like the scale is correct now :) 

hmm.. looks like the slice renderer doesn't work well when the dataset is scaled. Thank you for noticing!
I'll have a look at it.

**Comment by mlavik1** [comment] 2020-09-01 09:28
Ok, I just pushed a temporary fix. Does that solve the issue?

**Comment by SDSZR** [comment] 2020-09-01 09:37
Hello, I pulled it down, what do I need to do? Regenerate VolumeRenderedObject?

**Comment by SDSZR** [comment] 2020-09-01 09:46
Hi, I regenerated a Volume Rendered Object. This problem seems to be fixed, but why does the previous problem appear when I manually change the SlicingPlane(Clone) position? Can this be modified?
![image](https://user-images.githubusercontent.com/11844783/91834566-d1e78e00-ec7a-11ea-8ac8-20d39ee526ca.png)
Manual drag SlicingPlane(Clone) position：

![image](https://user-images.githubusercontent.com/11844783/91834736-03605980-ec7b-11ea-99d2-10ca00761beb.png)
![image](https://user-images.githubusercontent.com/11844783/91834753-09eed100-ec7b-11ea-9b8e-a1d8427166b1.png)

**Comment by mlavik1** [comment] 2020-09-12 13:07
Hi! And sorry for the late reply again. I should hopefully start replying faster now! (was busy taking driving lessons after work, but just finished it 😄)
I haven't been able to reproduce that issue yet, but I have a question:
Is that the "Slice renderer" spawned from this menu?
![image](https://user-images.githubusercontent.com/6906872/92996122-54890c80-f509-11ea-93ee-70d8ecf2e402.png)
I'm asking, because in your picture I can't see the 3D volume - only the slice view.
For me it looks like this:

![image](https://user-images.githubusercontent.com/6906872/92996140-7e423380-f509-11ea-8e74-c20cbd71f341.png)

Either way, I want to re-write that shader. I'm stating on it now, and hopefully that should help :)

**Comment by mlavik1** [comment] 2020-09-12 13:57
Ok, so after thinking twice I'm pretty sure this was caused by the volume texture using TextureWrapMode.Clamp. I wonder why I didn't get the same issue on my side.. However I have pushed a fix for it (and also cleaned up the shader a bit). Could you try again once more? 😁

**Comment by SDSZR** [comment] 2020-09-15 03:29
Haha, I’m here again. I saw that you haven’t responded before. I guess you are busy with other things. No matter what, thank you for your reply. During this period of use, I have encountered other problems. I hope you If you have time to help, thank you again! The problem is as follows:
![image](https://user-images.githubusercontent.com/11844783/93161965-4a078680-f746-11ea-8b8f-e2e6a1acd7ad.png)
The default initial size of the generated SlicingPlane does not match the generated volume data.

**Comment by mlavik1** [comment] 2020-09-15 06:56
Hello again~
Thanks for finding and reporting so many issues! :) 

Apparently the slicing plane kept it's original world scale. I have pushed a fix now :) 
I guess the slice renderer view (to the right in your picture) should ideally also scale with the model? (and not have a fixed resolution). I'll take a look at that next.
Also, did my previous fix work for you?

Have a nice day!

**Comment by SDSZR** [comment] 2020-09-15 08:53
Hi! I have good news here. The problems I gave you before and my feedback in the morning have been dealt with. After I pull the latest program, it is normal. Thank you for your help. I hope to continue to exchange related technologies with you. , I even have the urge to worship you as a teacher, thank you again for your prompt reply, and have a nice day!
oh，I almost forgot, the following is a screenshot of the normal display:
![image](https://user-images.githubusercontent.com/11844783/93188786-ff046800-f773-11ea-89c0-c46c3c4cec5e.png)

**Comment by SDSZR** [comment] 2020-09-15 09:16
I'm very sorry, I just found a new problem, that is, the generated cut image is different from the actual one, it feels like it is stretched, as shown in the following figure:
![image](https://user-images.githubusercontent.com/11844783/93191417-1002a880-f777-11ea-8f09-e20b44bea64e.png)
![image](https://user-images.githubusercontent.com/11844783/93191481-24df3c00-f777-11ea-913d-8b20d6a8884c.png)

**Comment by mlavik1** [comment] 2020-09-19 13:10
Thank you very much for the kind words :) 
And I'm happy to hear that it solved the problems!

Hmm.. that's strange. My first guess would be that it's the volume rendering shader that is wrong (since the slice rendering is quite straight forward), but I'll take a look at it. Hopefully I can get some time this weekend.

And again, thanks for finding all these bugs and reporting them to me :)

**Comment by mlavik1** [comment] 2020-10-07 21:18
**Update:** Sorry, I didn't get time to look at this yet :bow: 
My wife and I are expecting a child soon so it has been busy, and it will probably be busy the first two weeks after she is born. After that I will start going to office, and I will hopefully get time to work on this then (I usually work on my projects while sitting on the train :grin: )

Again, thanks for reporting the bug!

**Comment by mlavik1** [comment] 2020-10-09 18:41
Hi again!
Sorry for the long wait.
I just pushed a temporary fix to this branch: issue-24-slicerenderer.
I think that should fix the issue! I'll merge it into master once I have a more proper fix, and have been able to test it more.

**Comment by SDSZR** [comment] 2020-10-10 07:45
Hi，Thank you for still solving the problem in your busy schedule. Congratulations in advance for upgrading to become a dad. I downloaded the branch you submitted and the problem has been resolved. Thank you again and hope you have a good day.
![image](https://user-images.githubusercontent.com/11844783/95649345-aa080780-0b0f-11eb-936c-23ebfa8c7e03.png)

**Comment by mlavik1** [comment] 2020-10-10 08:13
Good to hear!
I will clean up the code a little bit more, and then merge into master.
谢谢! :grin: 
(I saw you have some repositories so in Chinese, so you can speak it right? I'm learning Chinese!)

Have a good day too!

**Comment by SDSZR** [comment] 2020-10-12 01:47
Haha, I am Chinese, so my github repositories has Chinese. You are welcome to learn Chinese and understand Chinese culture through learning. Of course, if you need help in the process of learning Chinese, I will be happy to answer you.

**Comment by SDSZR** [comment] 2020-10-12 01:51
Hi，There is one more question, I hope you can help answer it, the CT image should look like this:
![image](https://user-images.githubusercontent.com/11844783/95697182-71337400-0c70-11eb-9707-df04d09031e7.png)
Can an image like this be generated?

**Comment by mlavik1** [comment] 2020-10-13 16:27
And if you move them closer to each others you can change the contrast:
![image](https://user-images.githubusercontent.com/6906872/95888694-b4313c80-0d81-11eb-92c9-e45f3ce4a750.png)

**Comment by mlavik1** [comment] 2020-10-13 16:30
Here is an example of a TF (just unzip it and load it from the TF editor).
[blackwhite.zip](https://github.com/mlavik1/UnityVolumeRendering/files/5372779/blackwhite.zip)

Because of a bug you need to load it before creating the slice (or remove the slice and add a new one after loading it). I'll fix that later :)

**Comment by SDSZR** [comment] 2020-10-14 02:10
Thank you very much for your patient answers. According to your steps, I have achieved the effect as shown in the figure below. This effect is already very good, but I have two questions about generating images:
1. Why is the background not pure black?
2. Why are there other shadows in the generated image?
![image](https://user-images.githubusercontent.com/11844783/95935222-534b4800-0e05-11eb-9ee6-8681fc23bf08.png)

**Comment by mlavik1** [comment] 2020-10-20 09:58
hmm it's hard to say without having access to the model. If it's not skin or clothes, then could be some kind of noise in the data (I have seen that on some models).
You could try using the "isosurface" render mode, and change the visibility range slider, like this: https://youtu.be/1pIvmhXPh0w?t=45
Maybe you will be able to see something there?

**Closed** 2021-12-31 10:50 UTC
